version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Download the source code from the main repository
      - git clone https://github.com/Oaklight/ToolRegistry.git src_repo
      - mkdir -p src
      - cp -r src_repo/src/toolregistry src/
      - rm -rf src_repo

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
