import json
import uuid
import warnings
from typing import Any, Literal

from collections.abc import Callable

from pydantic import BaseModel, ValidationError, field_serializer


def _to_dict(obj: Any) -> Any:
    """Convert a Pydantic model or similar object to a dict.

    Args:
        obj: Object to convert. Pydantic models, legacy models with
            ``.dict()``, and plain dicts/values are all accepted.

    Returns:
        A dict representation, or the original object if no conversion
        method is available.
    """
    if hasattr(obj, "model_dump"):
        return obj.model_dump()
    if hasattr(obj, "dict"):
        return obj.dict()
    return obj


class ToolCall(BaseModel):
    id: str
    """The ID of the tool call."""
    name: str
    """The name of the function to call."""
    arguments: str
    """The arguments to call the function with, as generated by the model in JSON format."""
    type: Literal["function", "custom"] = "function"
    """The type of the tool call. Either 'function' or 'custom'."""

    @classmethod
    def _try_pydantic_formats(cls, tool_call_dict: dict) -> "ToolCall | None":
        """Attempt Pydantic model validation against known formats.

        Args:
            tool_call_dict: Dict representation of a tool call.

        Returns:
            A ToolCall if validation succeeds, None otherwise.
        """
        from .openai.chat_completion import (
            ChatCompletionMessageCustomToolCall,
            ChatCompletionMessageFunctionToolCall,
        )
        from .openai.response import ResponseFunctionToolCall

        validators: list[tuple[type[BaseModel], str, Callable[..., ToolCall]]] = [
            (
                ChatCompletionMessageFunctionToolCall,
                "function",
                lambda v: cls(
                    id=v.id,
                    name=v.function.name,
                    arguments=v.function.arguments,
                    type="function",
                ),
            ),
            (
                ChatCompletionMessageCustomToolCall,
                "custom",
                lambda v: cls(
                    id=v.id,
                    name=v.custom.name,
                    arguments=v.custom.input,
                    type="custom",
                ),
            ),
            (
                ResponseFunctionToolCall,
                "function",
                lambda v: cls(
                    id=v.call_id,
                    name=v.name,
                    arguments=v.arguments,
                    type="function",
                ),
            ),
        ]
        for model_cls, _, extractor in validators:
            try:
                validated = model_cls.model_validate(tool_call_dict)
                return extractor(validated)
            except (ValidationError, AttributeError, TypeError):
                continue
        return None

    @classmethod
    def _try_attribute_access(cls, tool_call: Any) -> "ToolCall | None":
        """Fallback: build ToolCall via direct attribute access.

        Args:
            tool_call: Raw tool call object.

        Returns:
            A ToolCall if attributes match a known format, None otherwise.
        """
        try:
            if hasattr(tool_call, "function") and hasattr(tool_call, "id"):
                return cls(
                    id=tool_call.id,
                    name=tool_call.function.name,
                    arguments=tool_call.function.arguments,
                    type="function",
                )
            if hasattr(tool_call, "custom") and hasattr(tool_call, "id"):
                return cls(
                    id=tool_call.id,
                    name=tool_call.custom.name,
                    arguments=tool_call.custom.input,
                    type="custom",
                )
            if hasattr(tool_call, "call_id") and hasattr(tool_call, "name"):
                return cls(
                    id=tool_call.call_id,
                    name=tool_call.name,
                    arguments=tool_call.arguments,
                    type="function",
                )
        except AttributeError:
            pass
        return None

    @classmethod
    def _try_vendor_dict(cls, tool_call_dict: dict) -> "ToolCall | None":
        """Try Anthropic tool_use or Gemini functionCall dict formats.

        Args:
            tool_call_dict: Dict representation of a tool call.

        Returns:
            A ToolCall if the dict matches a vendor format, None otherwise.
        """
        if not isinstance(tool_call_dict, dict):
            return None

        # Anthropic tool_use block
        if tool_call_dict.get("type") in ("tool_use", "server_tool_use"):
            return cls(
                id=tool_call_dict.get("id", ""),
                name=tool_call_dict.get("name", ""),
                arguments=json.dumps(tool_call_dict.get("input", {})),
                type="function",
            )

        # Gemini functionCall part
        if "functionCall" in tool_call_dict or "function_call" in tool_call_dict:
            fc = tool_call_dict.get("functionCall") or tool_call_dict.get(
                "function_call"
            )
            if fc:
                return cls(
                    id=fc.get("id", uuid.uuid4().hex[:24]),
                    name=fc.get("name", ""),
                    arguments=json.dumps(fc.get("args", {})),
                    type="function",
                )

        return None

    @classmethod
    def from_tool_call(cls, tool_call: Any) -> "ToolCall":
        """Convert various tool call formats to ToolCall using Pydantic validation.

        Supports the following formats:
        - ChatCompletionMessageFunctionToolCall (function calls)
        - ChatCompletionMessageCustomToolCall (custom calls)
        - ResponseFunctionToolCall (response API format)
        - Anthropic tool_use / server_tool_use blocks
        - Gemini functionCall parts
        - Dictionary representations of the above

        Args:
            tool_call: Tool call object in various formats (Pydantic models or dicts)

        Returns:
            ToolCall: Normalized tool call object with proper type classification

        Raises:
            TypeError: If the tool call format is not supported
        """
        tool_call_dict = _to_dict(tool_call)

        result = cls._try_pydantic_formats(tool_call_dict)
        if result is not None:
            return result

        result = cls._try_attribute_access(tool_call)
        if result is not None:
            return result

        result = cls._try_vendor_dict(tool_call_dict)
        if result is not None:
            return result

        raise TypeError(
            f"Unsupported tool call format. Expected ChatCompletionMessageFunctionToolCall, "
            f"ChatCompletionMessageCustomToolCall, ResponseFunctionToolCall, "
            f"Anthropic tool_use block, or Gemini functionCall part, got {type(tool_call)}"
        )


class ToolCallResult(BaseModel):
    id: str
    """The ID of the tool call."""
    result: Any
    """The result of the tool call."""

    @field_serializer("result")
    def convert_any_field_to_str(self, value: Any) -> str:
        """Convert `result` to string during serialization.

        Args:
            value: Current value of `any_field`.

        Returns:
            str: String representation of the field.
        """
        # simple case for now, can be extended to handle more complex cases
        return str(value)


API_FORMATS = Literal[
    "openai",  # deprecated, alias for openai-chat
    "openai-chat",  # chat completion (canonical)
    "openai-chatcompletion",  # deprecated, alias for openai-chat
    "openai-response",
    "anthropic",
    "gemini",
]

_DEPRECATED_API_FORMATS: dict[str, API_FORMATS] = {
    "openai": "openai-chat",
    "openai-chatcompletion": "openai-chat",
}


def _normalize_api_format(api_format: API_FORMATS) -> API_FORMATS:
    """Map deprecated format names to their canonical equivalents.

    Emits a ``DeprecationWarning`` when a deprecated name is used.
    """
    canonical = _DEPRECATED_API_FORMATS.get(api_format)
    if canonical is not None:
        warnings.warn(
            f'api_format="{api_format}" is deprecated, use "{canonical}" instead.',
            DeprecationWarning,
            stacklevel=3,
        )
        return canonical
    return api_format


def convert_tool_calls(tool_calls: list[Any]) -> list[ToolCall]:
    """Convert a list of tool calls into a list of ToolCall objects.

    Args:
        tool_calls (List[Any]): A list of tool call objects to convert.

    Returns:
        List[ToolCall]: A list of converted ToolCall objects.
    """
    return [ToolCall.from_tool_call(tool_call) for tool_call in tool_calls]


def _build_assistant_openai_chat(tool_calls: list[ToolCall]) -> list[dict[str, Any]]:
    """Build assistant message in OpenAI chat completion format."""
    from .openai.chat_completion import (
        ChatCompletionMessage,
        ChatCompletionMessageCustomToolCall,
        ChatCompletionMessageFunctionToolCall,
        Custom,
        Function,
    )

    chat_tool_calls: list = []
    for tc in tool_calls:
        if not tc.name or not tc.arguments:
            continue
        if tc.type == "function":
            chat_tool_calls.append(
                ChatCompletionMessageFunctionToolCall(
                    id=tc.id,
                    function=Function(name=tc.name, arguments=tc.arguments),
                )
            )
        elif tc.type == "custom":
            chat_tool_calls.append(
                ChatCompletionMessageCustomToolCall(
                    id=tc.id,
                    custom=Custom(name=tc.name, input=tc.arguments),
                )
            )
    return [ChatCompletionMessage(tool_calls=chat_tool_calls).model_dump()]


def _build_assistant_openai_response(
    tool_calls: list[ToolCall],
) -> list[dict[str, Any]]:
    """Build assistant message in OpenAI response format."""
    from .openai.response import ResponseFunctionToolCall

    return [
        ResponseFunctionToolCall(
            call_id=tc.id,
            name=tc.name,
            arguments=tc.arguments,
        ).model_dump()
        for tc in tool_calls
    ]


def _build_assistant_anthropic(tool_calls: list[ToolCall]) -> list[dict[str, Any]]:
    """Build assistant message in Anthropic format."""
    content = []
    for tc in tool_calls:
        if not tc.name or not tc.arguments:
            continue
        content.append(
            {
                "type": "tool_use",
                "id": tc.id,
                "name": tc.name,
                "input": json.loads(tc.arguments),
            }
        )
    return [{"role": "assistant", "content": content}]


def _build_assistant_gemini(tool_calls: list[ToolCall]) -> list[dict[str, Any]]:
    """Build assistant message in Gemini format."""
    parts = []
    for tc in tool_calls:
        if not tc.name or not tc.arguments:
            continue
        parts.append(
            {"functionCall": {"name": tc.name, "args": json.loads(tc.arguments)}}
        )
    return [{"role": "model", "parts": parts}]


def build_assistant_message(
    tool_calls: list[ToolCall],
    *,
    api_format: API_FORMATS = "openai-chat",
) -> list[dict[str, Any]]:
    """Build the assistant message from tool calls in various API formats.

    Reconstructs the assistant-side message containing tool call requests
    in the target API format.  This function only handles the tool-call
    portion of the assistant message; content, thinking, reasoning, and
    other vendor-specific fields must be preserved by the caller from the
    original LLM response.

    Args:
        tool_calls: A list of ToolCall objects (may contain mixed types).
        api_format: Target API format. Defaults to ``"openai-chat"``.

    Returns:
        The assistant message as a list of dicts in the specified API format.

    Raises:
        ValueError: If the API format is unsupported.
    """
    api_format = _normalize_api_format(api_format)
    builders: dict[str, Any] = {
        "openai-chat": _build_assistant_openai_chat,
        "openai-response": _build_assistant_openai_response,
        "anthropic": _build_assistant_anthropic,
        "gemini": _build_assistant_gemini,
    }
    builder = builders.get(api_format)
    if builder is None:
        raise ValueError(f"Unsupported API format: {api_format}")
    return builder(tool_calls)


def build_tool_response(
    tool_responses: dict[str, str | list],
    *,
    api_format: API_FORMATS = "openai-chat",
    tool_calls: list[ToolCall] | None = None,
) -> list[dict[str, Any]]:
    """Build tool result messages from tool execution responses.

    Reconstructs the tool-result messages needed by the LLM to process
    function call outcomes.  For Gemini format, ``tool_calls`` must be
    provided to resolve function names (Gemini uses function names
    instead of call IDs).

    Values in *tool_responses* may be plain strings or
    ``list[ContentBlock]`` for multimodal results.  All formats
    receive text-only tool results; multimodal content should be
    expanded into a separate user message upstream via
    :func:`~toolregistry.types.content_blocks.expand_content_blocks`.

    Args:
        tool_responses: Mapping of tool call IDs to results (``str``
            or ``list[ContentBlock]``).
            Must preserve insertion order (guaranteed in Python 3.7+).
        api_format: Target API format. Defaults to ``"openai-chat"``.
        tool_calls: Optional ToolCall list for Gemini name resolution.
            Falls back to call_id when unavailable.

    Returns:
        Tool result messages in the specified API format.

    Raises:
        ValueError: If the API format is unsupported.
    """
    from .content_blocks import content_blocks_to_text, is_content_block_list

    def _to_text(result: str | list) -> str:
        """Convert a result to a text string."""
        if isinstance(result, list) and is_content_block_list(result):
            return content_blocks_to_text(result)
        return str(result)

    api_format = _normalize_api_format(api_format)
    if api_format == "openai-chat":
        from .openai.chat_completion import ChatCompetionMessageToolCallResult

        messages = []
        for call_id, result in tool_responses.items():
            tool_message = ChatCompetionMessageToolCallResult(
                tool_call_id=call_id,
                content=_to_text(result),
            )
            messages.append(tool_message.model_dump())
        return messages

    elif api_format == "openai-response":
        from .openai.response import ResponseFunctionToolCallResult

        messages = []
        for call_id, result in tool_responses.items():
            tool_message = ResponseFunctionToolCallResult(
                call_id=call_id,
                output=_to_text(result),
            )
            messages.append(tool_message.model_dump())
        return messages

    elif api_format == "anthropic":
        content = []
        for call_id, result in tool_responses.items():
            content.append(
                {
                    "type": "tool_result",
                    "tool_use_id": call_id,
                    "content": _to_text(result),
                }
            )
        return [{"role": "user", "content": content}]

    elif api_format == "gemini":
        # Build call_id → function_name mapping from tool_calls if available
        name_map: dict[str, str] = {}
        if tool_calls:
            name_map = {tc.id: tc.name for tc in tool_calls}

        parts = []
        for call_id, result in tool_responses.items():
            func_name = name_map.get(call_id, call_id)
            parts.append(
                {
                    "functionResponse": {
                        "name": func_name,
                        "response": {"output": _to_text(result)},
                    }
                }
            )
        return [{"role": "user", "parts": parts}]

    else:
        raise ValueError(f"Unsupported API format: {api_format}")


# ------------------------------------------------------------------
# Deprecated aliases (will be removed in a future major release)
# ------------------------------------------------------------------


def recover_assistant_message(
    tool_calls: list[ToolCall],
    *,
    api_format: API_FORMATS = "openai-chat",
) -> list[dict[str, Any]]:
    """Deprecated: use :func:`build_assistant_message` instead."""
    warnings.warn(
        "recover_assistant_message() is deprecated, use build_assistant_message() instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    return build_assistant_message(tool_calls, api_format=api_format)


def recover_tool_message(
    tool_responses: dict[str, str | list],
    *,
    api_format: API_FORMATS = "openai-chat",
    tool_calls: list[ToolCall] | None = None,
) -> list[dict[str, Any]]:
    """Deprecated: use :func:`build_tool_response` instead."""
    warnings.warn(
        "recover_tool_message() is deprecated, use build_tool_response() instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    return build_tool_response(
        tool_responses, api_format=api_format, tool_calls=tool_calls
    )
