version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - make -C docs/ regenerate
    build:
      html:
        - make -C docs/ html

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
